name: Common Checks

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check-ceql-query-grammar-up-to-date:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.os }}
          create-symlink: true

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "19.1.7"

      - name: Install libtinfo5 for clang
        run: |
          sudo apt update
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo apt install ./libtinfo5_6.3-2ubuntu0.1_amd64.deb

      - name: Set up GCC
        run: |
          sudo apt install gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 60 --slave /usr/bin/g++ g++ /usr/bin/g++-14 && sudo update-alternatives --config gcc

      - name: Check versions
        run: |
          clang --version
          clang-format --version
          gcc -v

      - name: install dependencies
        run: chmod +x ./scripts/install_dependencies.sh && ./scripts/install_dependencies.sh

      - name: base build
        run: chmod +x ./scripts/build.sh && ./scripts/build.sh

      - name: check if grammar autogenerated is up to date
        run: |
          FOLDER_TO_CHECK="./src/core_server/internal/parsing/ceql_query/autogenerated/"
          INITIAL_CHECKSUM=$(find "$FOLDER_TO_CHECK" -type f -exec md5sum {} \; | sort -k 2 | md5sum)

          # generate grammar
          chmod +x ./scripts/build_grammar.sh
          ./scripts/build_grammar.sh

          # Wait just in case
          sleep 2

          FINAL_CHECKSUM=$(find "$FOLDER_TO_CHECK" -type f -exec md5sum {} \; | sort -k 2 | md5sum)

          if [ "$INITIAL_CHECKSUM" != "$FINAL_CHECKSUM" ]; then
          echo "Error: $FOLDER_TO_CHECK changed after compiling."
          exit 1
          else
          echo "$FOLDER_TO_CHECK has not changed."
          fi
  check-code-format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.os }}
          create-symlink: true

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "19.1.7"

      - name: Install libtinfo5 for clang
        run: |
          sudo apt update
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo apt install ./libtinfo5_6.3-2ubuntu0.1_amd64.deb

      - name: Set up GCC
        run: |
          sudo apt install gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 60 --slave /usr/bin/g++ g++ /usr/bin/g++-14 && sudo update-alternatives --config gcc

      - name: Check versions
        run: |
          clang --version
          clang-format --version
          gcc -v

      - name: Check clang-format version
        run: clang-format --version

      - name: Check code format
        run: |
          chmod +x ./scripts/clang_format_all_files.sh
          ./scripts/clang_format_all_files.sh
  check-clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Maximize build space
        uses: easimon/maximize-build-space@v10
        with:
          overprovision-lvm: true
          remove-dotnet: true
          remove-android: true

      - name: Check out repository code
        uses: actions/checkout@v3

      - name: ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ github.job }}-${{ matrix.os }}
          create-symlink: true

      - name: Install LLVM and Clang
        uses: KyleMayes/install-llvm-action@v2
        with:
          version: "19.1.7"

      - name: Install libtinfo5 for clang
        run: |
          sudo apt update
          wget http://security.ubuntu.com/ubuntu/pool/universe/n/ncurses/libtinfo5_6.3-2ubuntu0.1_amd64.deb
          sudo apt install ./libtinfo5_6.3-2ubuntu0.1_amd64.deb

      - name: Set up GCC
        run: |
          sudo apt install gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 60 --slave /usr/bin/g++ g++ /usr/bin/g++-14 && sudo update-alternatives --config gcc

      - name: Check versions
        run: |
          clang --version
          clang-format --version
          gcc -v

      - name: clang tidy version
        run: clang-tidy --version

      - name: clang tidy location
        run: which clang-tidy

      - name: install dependencies
        run: chmod +x ./scripts/install_dependencies.sh && ./scripts/install_dependencies.sh

      - name: base build
        run: chmod +x ./scripts/build.sh && ./scripts/build.sh

      - name: build with grammar
        run: chmod +x ./scripts/build_grammar.sh && ./scripts/build_grammar.sh

      - name: setup compile commands
        run: ln -s -r build/Debug/compile_commands.json compile_commands.json

      - name: Check clang tidy
        run: |
          chmod +x ./scripts/clang_tidy_check_all_files.sh
          ./scripts/clang_tidy_check_all_files.sh
